#!/bin/bash
# Copyright (c) 2000-2021 Synology Inc. All rights reserved.

PKG_NAME="bacula"
INST_DIR="/tmp/_${PKG_NAME}"
PKG_DIR="/tmp/_${PKG_NAME}_pkg"
PKG_DEST="/image/packages"

PrepareDirs() {
    for dir in $INST_DIR $PKG_DIR; do
        rm -rf "$dir"
    done
    for dir in $INST_DIR $PKG_DIR $PKG_DEST; do
        mkdir -p "$dir"
    done
}

SetupPackageFiles() {
    make install DESTDIR=${INST_DIR}
    mv ${INST_DIR}/sbin ${INST_DIR}/bin
    mv ${INST_DIR}/usr/lib ${INST_DIR}/lib
    rm ${INST_DIR}/lib/*.a
    cp /usr/lib/libacl.so.1 ${INST_DIR}/lib
    cp /usr/lib/libssl.so.1.0.0 ${INST_DIR}/lib
    cp /usr/lib/libcrypto.so.1.0.0 ${INST_DIR}/lib
    cp /usr/lib/libncurses.so.5 ${INST_DIR}/lib
    cp /usr/lib/libncursesw.so.5 ${INST_DIR}/lib
    synology/INFO.sh > INFO
    cp INFO "${PKG_DIR}"
    cp -r synology/conf/ "${PKG_DIR}"
    cp -r synology/scripts/ "${PKG_DIR}"
    cp synology/PACKAGE_ICON{,_256}.PNG "${PKG_DIR}"
}

MakePackage() {
    source /pkgscripts-ng/include/pkg_util.sh
    pkg_make_package $INST_DIR $PKG_DIR
    pkg_make_spk $PKG_DIR $PKG_DEST
}

main() {
    PrepareDirs
    SetupPackageFiles
    MakePackage
}

main "$@"
